apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tailscale
  name: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      containers:
        - image: tailscale/tailscale:stable
          imagePullPolicy: IfNotPresent
          name: tailscale
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
  name: tailscale
  labels:
    app: tailscale
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: tailscale
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: supermario
  name: supermario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermario
  template:
    metadata:
      labels:
        app: supermario
    spec:
      containers:
        - image: thtom/supermario:latest
          imagePullPolicy: IfNotPresent
          name: supermario
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: supermario
  labels:
    app: supermario
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: supermario
